### ISSUE TITLE
API vars not filled in in Access your ARO Cluster section

### ISSUE THREAD

**Issue by augustrh** [rhpds/bookbag-aro-mobb#6]
The Sample Output blocks for the following sections contain %aro_api% instead of an actual value.

Login to the OpenShift Web Console
![Screenshot 2023-12-06 at 13 31 36](https://github.com/rhpds/bookbag-aro-mobb/assets/15825212/b037c11a-7214-4ff3-94ea-9a427070ff78)

Login to the OpenShift CLI
![Screenshot 2023-12-06 at 13 29 56](https://github.com/rhpds/bookbag-aro-mobb/assets/15825212/28d5af85-9f79-46a8-b727-ef25331d7e7c)

**Comment by wkulhanek** [comment]
Should be fixed by adding `subs=attributes` to the [source] block.
